---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: OS-specific tasks
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Install Docker Engine
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present

- name: Manage Docker Engine configuration
  import_tasks: configure.yml

- name: Manage Docker Engine service
  import_tasks: service.yml

- name: Install Docker Compose (v2)
  ansible.builtin.package:
    name: "{{ docker_compose_package }}"
    state: present
  when: docker_compose_install