---
- name: Ensure Docker Engine service override directory exists
  ansible.builtin.file:
    path: "/etc/systemd/system/docker.service.d"
    state: directory
    owner: root
    group: root
    mode: '0644'

- name: Ensure Docker Engine service override configuration exists
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: '0644'

- name: Ensure Docker Engine is enabled on boot and started
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: yes
    daemon_reload: yes