---
- name: Ensure Docker Engine custom service unit exists
  ansible.builtin.template:
    src: docker.service.j2
    dest: /etc/systemd/system/docker.service
    owner: root
    group: root
    mode: '0644'
  notify: Restart Docker

- name: Ensure Docker Engine is enabled on boot and started
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: yes
    daemon_reload: yes